{
 "title": "Route53",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "account_id",
    "label": "account_ids",
    "query": "SELECT distinct(account_id) from public.aws_route53_hosted_zones;"
   },
   {
    "name": "zone",
    "label": "zone_name",
    "query": "SELECT distinct name from public.aws_route53_hosted_zones;"
   }
  ]
 },
 "panels": [
  {
   "title": "Total DNS Records",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(name) from aws_route53_hosted_zone_resource_record_sets WHERE hosted_zone_cq_id IN (SELECT cq_id from aws_route53_hosted_zones WHERE name IN (${zone}))"
    }
   ]
  },
  {
   "title": "Total Hosted Zones",
   "type": "stat",
   "description": "Total Hosted Zones",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(name) from aws_route53_hosted_zones WHERE account_id IN (${account_id})"
    }
   ]
  },
  {
   "title": "Account and Zones",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT account_id as Account, name as Zone, config_private_zone AS Private FROM aws_route53_hosted_zones WHERE (account_id in (${account_id}) and name in (${zone}))"
    }
   ]
  },
  {
   "title": "Account Name",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT account_id, aliases FROM aws_accounts WHERE account_id in (${account_id})"
    }
   ]
  },
  {
   "title": "Records",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT name, type, dns_name, resource_records from aws_route53_hosted_zone_resource_record_sets WHERE hosted_zone_cq_id IN (SELECT cq_id from aws_route53_hosted_zones WHERE name IN (${zone}))"
    }
   ]
  }
 ]
}